import type { MarketplaceApp } from './types';
import { createDefaultTier0SyncValues } from './tier0-sync';

export const APP_MARKETPLACE_MANIFEST: MarketplaceApp[] = [
  {
    id: 'openems',
    name: 'OpenEMS',
    nameKey: 'marketplace.app.openems.name',
    description: 'Deploy OpenEMS Edge and optionally connect the official OpenEMS UI using the Docker topology.',
    descriptionKey: 'marketplace.app.openems.description',
    version: 'latest',
    status: 'install',
    docsUrl: 'https://openems.github.io/openems.io/openems/latest/edge/deploy/docker.html',
    launchUrl: '/app-marketplace',
    deployFields: [
      {
        key: 'deploymentProfile',
        label: 'Deployment Profile',
        labelKey: 'marketplace.field.deploymentProfile.label',
        placeholder: 'Select deployment profile',
        placeholderKey: 'marketplace.field.deploymentProfile.placeholder',
        type: 'select',
        defaultValue: 'edge-ui',
        required: true,
        options: [
          { label: 'Edge + UI', labelKey: 'marketplace.field.deploymentProfile.edgeUi', value: 'edge-ui' },
          { label: 'Edge Only', labelKey: 'marketplace.field.deploymentProfile.edgeOnly', value: 'edge-only' },
        ],
      },
      {
        key: 'edgeServiceName',
        label: 'Edge Service Name',
        labelKey: 'marketplace.field.edgeServiceName.label',
        placeholder: 'openems-edge',
        placeholderKey: 'marketplace.field.edgeServiceName.placeholder',
        defaultValue: 'openems-edge',
        required: true,
      },
      {
        key: 'edgeImage',
        label: 'Edge Image',
        labelKey: 'marketplace.field.edgeImage.label',
        placeholder: 'openems/edge:latest',
        placeholderKey: 'marketplace.field.edgeImage.placeholder',
        defaultValue: 'openems/edge:latest',
        required: true,
      },
      {
        key: 'edgeContainerName',
        label: 'Edge Container Name',
        labelKey: 'marketplace.field.edgeContainerName.label',
        placeholder: 'openems_edge',
        placeholderKey: 'marketplace.field.edgeContainerName.placeholder',
        defaultValue: 'openems_edge',
        required: true,
      },
      {
        key: 'edgeFelixPort',
        label: 'Edge Felix Port',
        labelKey: 'marketplace.field.edgeFelixPort.label',
        placeholder: '18080',
        placeholderKey: 'marketplace.field.edgeFelixPort.placeholder',
        type: 'number',
        defaultValue: '18080',
        required: true,
      },
      {
        key: 'edgeWebsocketPort',
        label: 'Edge UI WebSocket Port',
        labelKey: 'marketplace.field.edgeWebsocketPort.label',
        placeholder: '18085',
        placeholderKey: 'marketplace.field.edgeWebsocketPort.placeholder',
        type: 'number',
        defaultValue: '18085',
        required: true,
      },
      {
        key: 'edgeRestPort',
        label: 'Edge REST API Port',
        labelKey: 'marketplace.field.edgeRestPort.label',
        placeholder: '18084',
        placeholderKey: 'marketplace.field.edgeRestPort.placeholder',
        type: 'number',
        defaultValue: '18084',
        required: true,
      },
      {
        key: 'edgeConfigVolume',
        label: 'Edge Config Volume',
        labelKey: 'marketplace.field.edgeConfigVolume.label',
        placeholder: 'openems-edge-conf',
        placeholderKey: 'marketplace.field.edgeConfigVolume.placeholder',
        defaultValue: 'openems-edge-conf',
        required: true,
      },
      {
        key: 'edgeDataVolume',
        label: 'Edge Data Volume',
        labelKey: 'marketplace.field.edgeDataVolume.label',
        placeholder: 'openems-edge-data',
        placeholderKey: 'marketplace.field.edgeDataVolume.placeholder',
        defaultValue: 'openems-edge-data',
        required: true,
      },
      {
        key: 'uiServiceName',
        label: 'UI Service Name',
        labelKey: 'marketplace.field.uiServiceName.label',
        placeholder: 'openems-ui',
        placeholderKey: 'marketplace.field.uiServiceName.placeholder',
        defaultValue: 'openems-ui',
      },
      {
        key: 'uiImage',
        label: 'UI Image',
        labelKey: 'marketplace.field.uiImage.label',
        placeholder: 'openems/ui-edge:latest',
        placeholderKey: 'marketplace.field.uiImage.placeholder',
        defaultValue: 'openems/ui-edge:latest',
      },
      {
        key: 'uiContainerName',
        label: 'UI Container Name',
        labelKey: 'marketplace.field.uiContainerName.label',
        placeholder: 'openems_ui',
        placeholderKey: 'marketplace.field.uiContainerName.placeholder',
        defaultValue: 'openems_ui',
      },
      {
        key: 'uiHttpPort',
        label: 'UI HTTP Port',
        labelKey: 'marketplace.field.uiHttpPort.label',
        placeholder: '18081',
        placeholderKey: 'marketplace.field.uiHttpPort.placeholder',
        type: 'number',
        defaultValue: '18081',
      },
      {
        key: 'uiHttpsPort',
        label: 'UI HTTPS Port',
        labelKey: 'marketplace.field.uiHttpsPort.label',
        placeholder: '18443',
        placeholderKey: 'marketplace.field.uiHttpsPort.placeholder',
        type: 'number',
        defaultValue: '18443',
      },
      {
        key: 'uiConfigVolume',
        label: 'UI Config Volume',
        labelKey: 'marketplace.field.uiConfigVolume.label',
        placeholder: 'openems-ui-conf',
        placeholderKey: 'marketplace.field.uiConfigVolume.placeholder',
        defaultValue: 'openems-ui-conf',
      },
      {
        key: 'uiLogVolume',
        label: 'UI Log Volume',
        labelKey: 'marketplace.field.uiLogVolume.label',
        placeholder: 'openems-ui-log',
        placeholderKey: 'marketplace.field.uiLogVolume.placeholder',
        defaultValue: 'openems-ui-log',
      },
      {
        key: 'websocketHost',
        label: 'UI WebSocket Host',
        labelKey: 'marketplace.field.websocketHost.label',
        placeholder: 'openems-edge',
        placeholderKey: 'marketplace.field.websocketHost.placeholder',
        defaultValue: 'openems-edge',
      },
      {
        key: 'websocketPort',
        label: 'UI WebSocket Port',
        labelKey: 'marketplace.field.websocketPort.label',
        placeholder: '8085',
        placeholderKey: 'marketplace.field.websocketPort.placeholder',
        type: 'number',
        defaultValue: '8085',
      },
    ],
    syncTemplate: createDefaultTier0SyncValues(),
  },
];
