import type { MarketplaceApp } from './types';

export const APP_MARKETPLACE_MANIFEST: MarketplaceApp[] = [
  {
    id: 'openems',
    name: 'OpenEMS',
    description: '基于官方 Docker 拓扑部署 OpenEMS Edge，并可选联动 OpenEMS UI。',
    version: 'latest',
    status: 'install',
    docsUrl: 'https://openems.github.io/openems.io/openems/latest/edge/deploy/docker.html',
    launchUrl: '/app-marketplace',
    deployFields: [
      {
        key: 'deploymentProfile',
        label: '部署模式',
        placeholder: '选择部署模式',
        type: 'select',
        defaultValue: 'edge-ui',
        required: true,
        options: [
          { label: 'Edge + UI', value: 'edge-ui' },
          { label: 'Edge Only', value: 'edge-only' },
        ],
      },
      {
        key: 'edgeServiceName',
        label: 'Edge 服务名',
        placeholder: 'openems-edge',
        defaultValue: 'openems-edge',
        required: true,
      },
      {
        key: 'edgeContainerName',
        label: 'Edge 容器名',
        placeholder: 'openems_edge',
        defaultValue: 'openems_edge',
        required: true,
      },
      {
        key: 'edgeFelixPort',
        label: 'Edge Felix 端口',
        placeholder: '8080',
        type: 'number',
        defaultValue: '8080',
        required: true,
      },
      {
        key: 'edgeWebsocketPort',
        label: 'Edge UI-Websocket 端口',
        placeholder: '8085',
        type: 'number',
        defaultValue: '8085',
        required: true,
      },
      {
        key: 'edgeConfigVolume',
        label: 'Edge 配置卷',
        placeholder: 'openems-edge-conf',
        defaultValue: 'openems-edge-conf',
        required: true,
      },
      {
        key: 'edgeDataVolume',
        label: 'Edge 数据卷',
        placeholder: 'openems-edge-data',
        defaultValue: 'openems-edge-data',
        required: true,
      },
      {
        key: 'uiServiceName',
        label: 'UI 服务名',
        placeholder: 'openems-ui',
        defaultValue: 'openems-ui',
      },
      {
        key: 'uiContainerName',
        label: 'UI 容器名',
        placeholder: 'openems_ui',
        defaultValue: 'openems_ui',
      },
      {
        key: 'uiHttpPort',
        label: 'UI HTTP 端口',
        placeholder: '80',
        type: 'number',
        defaultValue: '80',
      },
      {
        key: 'uiHttpsPort',
        label: 'UI HTTPS 端口',
        placeholder: '443',
        type: 'number',
        defaultValue: '443',
      },
      {
        key: 'uiConfigVolume',
        label: 'UI 配置卷',
        placeholder: 'openems-ui-conf',
        defaultValue: 'openems-ui-conf',
      },
      {
        key: 'uiLogVolume',
        label: 'UI 日志卷',
        placeholder: 'openems-ui-log',
        defaultValue: 'openems-ui-log',
      },
      {
        key: 'websocketHost',
        label: 'UI Websocket Host',
        placeholder: 'openems_edge',
        defaultValue: 'openems_edge',
      },
      {
        key: 'websocketPort',
        label: 'UI Websocket Port',
        placeholder: '8085',
        type: 'number',
        defaultValue: '8085',
      },
    ],
  },
];
